namespace PlatformerPro
{
	/// <summary>
	/// The types of event responses.
	/// </summary>
	public enum EventResponseType
	{
		DEBUG_LOG,
		SEND_MESSSAGE,
		ACTIVATE_GAMEOBJECT,
		DEACTIVATE_GAMEOBJECT,
		ENABLE_BEHAVIOUR,
		DISABLE_BEHAVIOUR,
		OVERRIDE_ANIMATON,
		CLEAR_ANIMATION_OVERRIDE,
		PLAY_PARTICLES,
		PAUSE_PARTICLES,
		SWITCH_SPRITE,
		PLAY_SFX,
		PLAY_SONG,
		STOP_SONG,
		MAKE_INVULNERABLE,
		MAKE_VULNERABLE,
		LEVEL_COMPLETE,
		LOAD_SCENE,
		LOCK,
		UNLOCK,
		RESPAWN,
		SET_ACTIVE_RESPAWN,
		START_EFFECT,
		FLIP_GRAVITY,
		SPECIAL_MOVE_ANIMATION,
		START_SWIM,
		STOP_SWIM,
		ADD_SCORE,
		RESET_SCORE,
		PLAY_ANIMATION,
		STOP_ANIMATION,
		UPDATE_LIVES,
		UPDATE_MAX_HEALTH,
		SET_MAX_HEALTH,
		UPDATE_MAX_LIVES,
		SET_MAX_LIVES,
		UPDATE_ITEM_MAX,
		SET_ITEM_MAX,
		SET_TAGGED_PROPERTY,
		ADD_TO_TAGGED_PROPERTY,
		MULTIPLY_TAGGED_PROPERTY,
		SPAWN_ITEM,
		ADD_VELOCITY,
		SET_VELOCITY
	}
}