// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_complete_winter_museum = "CgkIgYf6gpcYEAIQDQ"; // <GPGSID>
        public const string achievement_complete_wine_museum = "CgkIgYf6gpcYEAIQAg"; // <GPGSID>
        public const string leaderboard_viking_highscore = "CgkIgYf6gpcYEAIQDA"; // <GPGSID>
        public const string leaderboard_automobile_highscore = "CgkIgYf6gpcYEAIQCg"; // <GPGSID>
        public const string achievement_complete_automobile_museum = "CgkIgYf6gpcYEAIQAQ"; // <GPGSID>
        public const string leaderboard_winter_highscore = "CgkIgYf6gpcYEAIQDg"; // <GPGSID>
        public const string achievement_moving_100_times = "CgkIgYf6gpcYEAIQBA"; // <GPGSID>
        public const string leaderboard_wine_highscore = "CgkIgYf6gpcYEAIQCw"; // <GPGSID>
        public const string achievement_moving_1000_times = "CgkIgYf6gpcYEAIQBg"; // <GPGSID>
        public const string achievement_moving_500_times = "CgkIgYf6gpcYEAIQBQ"; // <GPGSID>
        public const string achievement_complete_first_lv11_exhibit = "CgkIgYf6gpcYEAIQCA"; // <GPGSID>
        public const string achievement_complete_viking_museum = "CgkIgYf6gpcYEAIQAw"; // <GPGSID>
        public const string achievement_complete_first_lv10_exhibit = "CgkIgYf6gpcYEAIQBw"; // <GPGSID>
        public const string achievement_complete_first_lv12_exhibit = "CgkIgYf6gpcYEAIQCQ"; // <GPGSID>

}

